apiVersion: apps/v1
kind: Deployment
metadata:
  name: people-deployment
  labels:
    app: people-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: people-app
  template:
    metadata:
      labels:
        app: people-app
    spec:
      containers:
        - name: people-app
          image: goofyahead/people-app:develop
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
