kind: ConfigMap
apiVersion: v1
metadata:
  name: company-service
data:
  application-kubernetes.yml: |-
    greetings:
      message: Hello to from kube profile
    farewell:
      message: Say Goodbye