spring:
  application:
    name: company-service

server:
  port: 0

greetings:
  message: well well well

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}